### PR TITLE
fix: match mui v0 styling with v4 buttons

### LINKED ISSUE #1199: Texter action buttons are squashed horizontally
**Describe the bug**

The texter action buttons are too close together.

**To Reproduce**

1.  Go to texter replies or past conversations assignment
2.  See squashed buttons

**Expected behavior**

There should be padding between the buttons as there was with MUI v0.

**Screenshots**

Screen Shot 2022-05-15 at 9 20 17 AM

**Additional context**

Regression from #1159.

### PR DESCRIPTION
**Pull request by ajohn25**
## Description
This updates the save button on the campaign edit page to be contained, and adds margins to buttons on the texter assignment page.

## Motivation and Context
Closes #1199

## How Has This Been Tested?
This has been tested locally.

## Screenshots (if appropriate):
<table>
<tr>
<th>Admin</th>
<th>Texter</th>
</tr>
<td>

</td>
<td>

</table>

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

### CODE REVIEW

File: src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx [hunk 1]
```diff
@@ -343,7 +343,7 @@ const CampaignInteractionStepsForm: React.FC<InnerProps> = (props) => {
       />
       <Button
         {...dataTest("interactionSubmit")}
-        variant="containted"
```
Comment (bchrobot) [inline src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx:346]: 🤦‍♂️

**Review by bchrobot — APPROVED** [review]

File: src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx (hunk 1 above)
Comment (bchrobot) [reply src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx:346]: Type-checking _should_ have caught that I think 🤔

**Review by henryk1229 — APPROVED** [review]
