### PR TITLE
fix(apply tag dialog): fix type errors

### LINKED ISSUE #1565: Fix apply tag dialog behavior
**Describe the bug**
The apply tag dialog behaves as though all tags are unassignable. See screenshot below from a texter who applied an assignable tag.
imageedit_1_3292725701

**To Reproduce**

1.  Assign replies to yourself
2.  Go to the texter view and apply an assignable tag
3.  See that the unassignable tag warning and dialog changes appear

**Expected behavior**
Show warning + dialog changes only when appropriate. In general, the dialog should behave the same as before #1530

**Additional context**
In #1530 we created the [`CampaignContactTag`](https://github.com/politics-rewired/Spoke/pull/1530/files#diff-868812c336d8f24e19d76d86e4e978d07c6ab0bcb8fec874168be90d4c1ce381) type and partially updated [`ApplyTagDialog.jsx`](https://github.com/politics-rewired/Spoke/pull/1530/files#diff-b6d94813933143bf72035dca9d66670f680e1dbbc24f881b671f12e3f0c21486) to use the new type. Currently, the behavior of the [`isNonAssignableTagApplied`](https://github.com/politics-rewired/Spoke/blob/main/src/containers/AssignmentTexterContact/components/ApplyTagDialog.jsx#L14) function has been confirmed to be incorrect, but there are also other locations not yet identified that need to be updated.

https://secure.helpscout.net/conversation/2151658082/8334?folderId=3196057
https://secure.helpscout.net/conversation/2151509788/8332?folderId=3196057

### PR DESCRIPTION
**Pull request by ajohn25**
## Description

This fixes type errors in the apply tag dialog component.

## Motivation and Context

Closes #1565 

## How Has This Been Tested?

This has been tested locally.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

### CODE REVIEW

**Comment by ajohn25** [comment]
Getting this up for review to unblock release of 6.1.0! There are some additional items to note for review here that I punted looking into in favor of fixing user facing behavior more quickly. If we have agreement on punting on these, we can turn them into followup issues:
1. Are the [unsafe React lifecycle methods](https://github.com/politics-rewired/Spoke/blob/main/src/containers/AssignmentTexterContact/components/ApplyTagDialog.jsx#L23-L32) no longer necessary with hook based state management or does this PR potentially introduce different unwanted component behavior?
2. What's going on under the hood with `tag.createdAt` to produce the GraphQL type error described in the [last error block here](https://github.com/politics-rewired/Spoke/issues/1565#issuecomment-1425041397)?

File: src/containers/TexterTodo/index.jsx [hunk 1]
```diff
@@ -45,7 +45,6 @@ const contactDataFragment = `
             confirmationSteps
             isAssignable
             isSystem
-            createdAt
```
Comment (bchrobot) [inline src/containers/TexterTodo/index.jsx:48]: Required: revert this change and instead check for `typeof === 'string'` in the `Tag.createdAt` resolver, converting to `Date` when necessary:

https://github.com/politics-rewired/Spoke/blob/7d9b801d19c8f6ce86d57f2b8770de1c0fca53d0/src/server/api/tag.ts#L25-L40

File: src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx [hunk 2]
```diff
@@ -0,0 +1,208 @@
...
+    CampaignContactTag | undefined
+  >(undefined);
+
+  const setPendingTag = (changedTag: Tag) => {
+    const changedContactTag = {
+      id: `${contact.id}-${changedTag.id}`,
+      tag: changedTag,
+      tagger: texter,
+      createdAt: Date.now().toString(),
+      updatedAt: Date.now().toString()
```
Comment (bchrobot) [inline src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx:59]: Required: pass ISO and not stringified integer timestamp

```suggestion
      createdAt: DateTime.now().toISO(),
      updatedAt: DateTime.now().toISO()
```

File: src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx [hunk 3]
```diff
@@ -0,0 +1,208 @@
...
+    setPendingContactTag(changedContactTag);
+  };
+
+  const addToSelectedTags = (addedTag: Tag) => {
+    const addedContactTag = {
+      id: `${contact.id}-${addedTag.id}`,
+      tag: addedTag,
+      tagger: texter,
+      createdAt: Date.now().toString(),
+      updatedAt: Date.now().toString()
```
Comment (bchrobot) [inline src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx:70]: Required: pass ISO and not stringified integer timestamp

```suggestion
      createdAt: DateTime.now().toISO(),
      updatedAt: DateTime.now().toISO()
```

File: src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+
+  const handleOnCancelEscalateTag = () => setPendingContactTag(undefined);
+
+  const handleOnConfirmAddEscalatedTag = (escalateTag: Tag) => {
+    if (
+      selectedContactTags.findIndex((t) => t.tag.id === escalateTag.id) === -1
+    ) {
+      addToSelectedTags(escalateTag);
+    }
+    handleOnCancelEscalateTag();
```
Comment (bchrobot) [inline src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx:91]: Suggestion: I think it's clearer to call `setPendingContactTag(undefined)` directly rather than a method named cancel within a method named confirm.

File: src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx [hunk 5]
```diff
@@ -0,0 +1,208 @@
...
+      (t) => !selectedTagIds.has(t.tag.id)
+    );
+
+    return [addedTags, removedTags];
+  };
+
+  const handleApplyTags = () => {
+    const [addedTags, removedTags] = getTagsPayload();
+    onApplyTag(addedTags, removedTags);
+    handleOnCancelEscalateTag();
```
Comment (bchrobot) [inline src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx:121]: Suggestion: I think it's clearer to call `setPendingContactTag(undefined)` directly rather than a function meant to be passed as callback

File: src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx [hunk 6]
```diff
@@ -0,0 +1,208 @@
...
+  };
+
+  const handleApplyTagsAndMoveOn = () => {
+    const [addedTags, removedTags] = getTagsPayload();
+    onApplyTagsAndMoveOn(addedTags, removedTags);
+    handleOnCancelEscalateTag();
```
Comment (bchrobot) [inline src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx:127]: Suggestion: I think it's clearer to call `setPendingContactTag(undefined)` directly rather than a function meant to be passed as callback

File: src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx [hunk 7]
```diff
@@ -0,0 +1,208 @@
...
+
+  const handleAddEscalatedTag = () => {
+    const escalateTag = allTags.find(isEscalateTag)!;
+
+    if (
+      escalateTag.confirmationSteps &&
+      escalateTag.confirmationSteps.length > 0
+    )
+      setPendingTag(escalateTag);
+    else handleOnConfirmAddEscalatedTag(escalateTag);
```
Comment (bchrobot) [inline src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx:102]: Required: use curly braces for if/else

File: src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx [hunk 8]
```diff
@@ -0,0 +1,208 @@
...
+    if (
+      selectedContactTags.findIndex((t) => t.tag.id === escalateTag.id) === -1
+    ) {
+      addToSelectedTags(escalateTag);
+    }
+    handleOnCancelEscalateTag();
+  };
+
+  const handleAddEscalatedTag = () => {
+    const escalateTag = allTags.find(isEscalateTag)!;
```
Comment (bchrobot) [inline src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx:95]: Suggestion: prefer an `undefined` check here, even though we never expect to encounter that

**Review by bchrobot — CHANGES_REQUESTED** [review]

File: src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx (hunk 4 above)
Comment (ajohn25) [reply src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx:91]: Agreee 👍🏾

**Review by bchrobot — APPROVED** [review]
Looks good!

**Review by hiemanshu — APPROVED** [review]
LGTM!
