### PR TITLE
fix: fix refresh integration button hidden

### LINKED ISSUE #1283: Refresh integration button hidden on some screens
**Describe the bug**

The "Refresh integration" button is hidden on smaller screens or for longer integration names. This is true even when left sidebar is collapsed.

**To Reproduce**

1.  Go to Integrations page
2.  Create an integration
3.  Collapse lefthand side bar
4. Shrink window width
5.  See that "Refresh Integration" button becomes inaccessible

**Expected behavior**

Refresh integration button should always be visible.

**Screenshots**

Screen_Shot_2022-06-22_at_11_09_48_AM

**Additional context**

Ref: https://secure.helpscout.net/conversation/1927626801/6628

### PR DESCRIPTION
**Pull request by hiemanshu**
## Description

Set text overflow to clip, so it doesn't convert buttons to ellipsis. 

## Motivation and Context

Fixes #1283 

## How Has This Been Tested?
Tested locally

## Screenshots (if appropriate):

Screenshot 2022-08-23 at 9 22 16 PM
Screenshot 2022-08-23 at 9 22 37 PM

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

### CODE REVIEW

**Comment by hiemanshu** [comment]
Screenshot 2022-08-24 at 12 53 00 PM

The smaller the window gets, the smaller the overall width decreases. Button is still visible, unusable on phones, but for other reasons (the whole UI doesn't work on phones)

**Comment by ninabaldwin** [comment]
@hiemanshu @bchrobot Can we change the top left refresh to say "refresh list" (that's what it does right?) and the ones on the right be called "sync" instead of "refresh sync"? And you can put refresh sync and edit into the overflow menu as needed.

**Comment by hiemanshu** [comment]
Screenshot 2022-08-25 at 3 24 28 PM

Screenshot 2022-08-25 at 3 25 11 PM


@bchrobot @politics-rewired/organizing I upgraded the Table to the newer MUI, and I think this looks better, without needing an overflow menu. Let me know what you think!

**Review by bchrobot — APPROVED** [review]
Looks good to me!

File: src/containers/AdminExternalSystems.tsx [hunk 1]
```diff
@@ -222,54 +221,57 @@ class AdminExternalSystems extends Component<Props, State> {
           variant="contained"
           endIcon={<RefreshIcon />}
           onClick={this.handleRefreshSystems}
+          style={{ marginTop: 15, marginBottom: 15 }}
         >
-          Refresh
+          Refresh Lists
```
Comment (ajohn25) [inline src/containers/AdminExternalSystems.tsx:226]: Organizing suggestion to make it as clear as we can it's the one list of integrations that are getting refreshed, not the integrations themselves

```suggestion
          Refresh List
```

**Review by ajohn25 — APPROVED** [review]
