### PR TITLE
fix: don't create a contacts upload job if contacts doesn't exist 

### LINKED ISSUE #678: Contacts module displays "Contact upload successful" before CSV is uploaded
* [x] I have searched through existing issues and did not find an existing report

### New campaigns display "Contact upload successful" by default under the Contacts tab of the Campaign Edit page, before the admin has uploaded a CSV.
**To Reproduce**

1. Go to Campaign Edit page of new campaign (copy and original)
1. Click on Contacts Module
1. See "Contact upload successful." below "Upload Messages"

**Expected behavior**
"Contact upload successful" would appear if and only if admin had uploaded a CSV.

**Desktop:**

* OS: iOS 10.15.4 
* Browser: Chrome

### PR DESCRIPTION
**Pull request by hiemanshu**
## Description

Fixes #678 

## Motivation and Context

Fixes #678 

## How Has This Been Tested?

Tested locally

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

### CODE REVIEW

**Review by bchrobot — COMMENTED** [review]
Question: it seems like this addresses the symptom (a misleading message being displayed) but not the problem (the existence of a contact upload job with a result message on a brand new campaign before contact upload has even been attempted)?

**Comment by hiemanshu** [comment]
> Question: it seems like this addresses the symptom (a misleading message being displayed) but not the problem (the existence of a contact upload job with a result message on a brand new campaign before contact upload has even been attempted)?

Yup, good point. Fixed it!

File: src/containers/AdminCampaignList.jsx [hunk 1]
```diff
@@ -54,7 +54,6 @@ class AdminCampaignList extends React.Component {
       description: "",
       dueBy: null,
       organizationId,
-      contacts: [],
```
Comment (bchrobot) [inline src/containers/AdminCampaignList.jsx:57]: Ahhhhhhhhh!

**Review by bchrobot — APPROVED** [review]
The mystery is solved! Looks great 👍
