### PR TITLE
fix: fix display of survey questions

### LINKED ISSUE #1115: Survey questions hidden with long conversation
**Describe the bug**

When the conversation gets long, the survey questions are hidden.

**To Reproduce**

1.  Go to long conversation in campaign with survey questions
2.  See that survey questions are hidden

**Expected behavior**

Survey questions should be visible and usable regardless of conversation length.

**Screenshots**

image

**Additional context**

Regression introduced by #1091. Material UI v4 elements have different flexbox behavior.

### PR DESCRIPTION
**Pull request by bchrobot**
## Description

This fixes conditional logic for displaying past survey questions.

It also sets the dropdown width to auto, addressing some user complaints, and makes expand/collapse icons more intuitive for vertically-expanding card.

## Motivation and Context

Previous logic did not handle the case of a single already answered survey question.

Closes #1115 .

## How Has This Been Tested?

This as been tested locally.

## Screenshots (if appropriate):

<table>
<tr>
<td>

Screenshot_3_18_22__11_41_AM

</td>
<td>

Screenshot_3_18_22__11_45_AM

</td>
</tr>
</table>

## Documentation Changes

N/A

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

### CODE REVIEW

File: src/components/AssignmentTexterSurveys.jsx [hunk 1]
```diff
@@ -143,6 +144,15 @@ class AssignmentTexterSurveys extends Component {
       ({ question }) => (question.text || "") !== ""
     );
 
+    const currentQuestion =
+      (currentInteractionStep.question.text || "") !== ""
```
Comment (hiemanshu) [inline src/components/AssignmentTexterSurveys.jsx:148]: suggestion: Use `isEmpty` from lodash

File: src/components/AssignmentTexterSurveys.jsx [hunk 2]
```diff
@@ -143,6 +144,15 @@ class AssignmentTexterSurveys extends Component {
...
+        ? currentInteractionStep
+        : undefined;
+
+    const pastQuestions = questions.filter(
+      (step) => step.id !== (currentQuestion || {}).id
```
Comment (hiemanshu) [inline src/components/AssignmentTexterSurveys.jsx:153]: Suggestion: Use safe navigation operator

**Review by hiemanshu — APPROVED** [review]
Couple of suggestions, otherwise LGTM!

File: src/components/AssignmentTexterSurveys.jsx (hunk 2 above)
Comment (bchrobot) [reply src/components/AssignmentTexterSurveys.jsx:153]: I remember this not working in `.js` files, but it does!
