### PR TITLE
fix: show all timezone options in dropdown

### LINKED ISSUE #1492: Time zone selection box limited entries
**Your issue may already be reported!**
Please search on the [issue tracker](../) before creating one.

- [x] I have searched through existing issues and did not find an existing report

**Describe the bug**
When creating a new campaign, trying to select a time zone only pulls up the first 4 entries and there is no way to scroll through the options.

**To Reproduce**

1.  Go to create a new campaign
2.  Click on Texting Hours
3.  In the time zone field, erase the current entry and notice that the popup list only has 4 options available to select.

**Expected behavior**
Should be able to view all options by scrolling or arrowing down.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows 11]
- Browser [Chrome]
- Version [106.0.5249.103 (Official Build) (64-bit)]

scrolling text hours

**Additional context**

### PR DESCRIPTION
**Pull request by bchrobot**
## Description

This removes the limit on number of autocomplete results to show in the dropdown.

## Motivation and Context

Closes #1492.

## How Has This Been Tested?

This has been tested locally; see screenshot.

## Screenshots (if appropriate):

Screenshot 2022-10-30 at 1 58 11 PM

## Documentation Changes

N/A

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203231165295649

### CODE REVIEW

File: src/containers/AdminCampaignEdit/sections/CampaignTextingHoursForm.tsx [hunk 1]
```diff
@@ -136,7 +136,6 @@ class CampaignTextingHoursForm extends React.Component<
         value: rawValue
       }))}
       filter={Autocomplete.caseInsensitiveFilter}
-      maxSearchResults={4}
```
Comment (ajohn25) [inline src/containers/AdminCampaignEdit/sections/CampaignTextingHoursForm.tsx:139]: Any idea why this was ever added lol?

**Review by ajohn25 — APPROVED** [review]

File: src/containers/AdminCampaignEdit/sections/CampaignTextingHoursForm.tsx (hunk 1 above)
Comment (bchrobot) [reply src/containers/AdminCampaignEdit/sections/CampaignTextingHoursForm.tsx:139]: Git blame says I did it 3 years ago. Couldn’t tell you why… ¯\_(ツ)_/¯

**Review by hiemanshu — APPROVED** [review]

**Comment by bengilvar** [comment]
Gave this a QA and the bug is fixed, All options available.
