### PR TITLE
fix: make disabled buttons unclickable

### LINKED ISSUE #781: Disabled buttons are still clickable
**Your issue may already be reported!**
Please search on the [issue tracker](../) before creating one.

- [x] I have searched through existing issues and did not find an existing report

**Describe the bug**

Some disabled buttons are still clickable.

**To Reproduce**

TBD

**Expected behavior**

Disabled buttons should actually be disabled.

**Screenshots**

N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by henryk1229**
## Description

Closes #781, part of Q4 feature freeze

## Motivation and Context

Unclickable buttons should be unclickable!

NB: For the edit campaign sections, It seems like there should be a better solution than extracting the form submit functionality into a button outside of the GSForm, but I spent a lot of time trying to properly disable the GSSubmitButton within the component itself and within the GSForm component, but couldn't crack it. 

## How Has This Been Tested?

Locally

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My commit messages follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

### CODE REVIEW

File: src/containers/Settings/components/General.jsx [hunk 1]
```diff
@@ -125,8 +127,12 @@ class Settings extends React.Component {
     }
   };
 
+  handleChangeOptOutMessage = (optOutMessage) => {
+    this.setState({ optOutMessage });
+  };
```
Comment (bchrobot) [inline src/containers/Settings/components/General.jsx:132]: The Opt Out Message `GSForm` should be changed to a controlled element if you're going to manage state (currently only `defaultValue` is passed to the form).

File: src/containers/Settings/components/General.jsx [hunk 2]
```diff
@@ -278,14 +302,15 @@ class Settings extends React.Component {
...
+                onChange={this.handleChangeOptOutMessage}
               />
             </CardText>
             <CardActions>
               <Form.Button
                 label={this.props.saveLabel || "Save Opt-Out Message"}
                 type="submit"
                 component={RaisedButton}
-                disabled={isWorking}
+                disabled={disableOptOutSave}
```
Comment (bchrobot) [inline src/containers/Settings/components/General.jsx:313]: The `disabled` option for this `GSForm` is working fine but not elsewhere?

File: src/containers/Settings/components/General.jsx [hunk 3]
```diff
@@ -125,8 +127,12 @@ class Settings extends React.Component {
     }
   };
 
+  handleChangeOptOutMessage = (optOutMessage) => {
+    this.setState({ optOutMessage });
+  };
+
   handleEditOptOutMessage = ({ optOutMessage }) =>
-    this.editSettings("Opt Out Messasge", { optOutMessage });
+    this.editSettings("Opt Out Message", { optOutMessage });
```
Comment (bchrobot) [inline src/containers/Settings/components/General.jsx:135]: 👍

**Review by bchrobot — CHANGES_REQUESTED** [review]

File: src/containers/Settings/components/General.jsx [hunk 4]
```diff
@@ -389,8 +401,13 @@ class Settings extends React.Component {
           <Card className={css(styles.sectionCard)}>
             <GSForm
               schema={trollbotSettingsSchema}
-              onSubmit={this.handleEditTrollBotUrl}
-              defaultValue={{ trollbotWebhookUrl }}
+              onSubmit={this.handleSaveTrollbotUrl}
```
Comment (bchrobot) [inline src/containers/Settings/components/General.jsx:404]: Is there a reason this `onSubmit` is kept (perhaps to support submitting with <kbd>enter</kbd> in addition to the button) but not others?

We want all fields to behave the same way for consistent UX unless there's a compelling reason for exception.

**Review by bchrobot — APPROVED** [review]
Looks good other than the one question/comment in this review

File: src/containers/Settings/components/General.jsx (hunk 4 above)
Comment (henryk1229) [reply src/containers/Settings/components/General.jsx]: oops - no compelling reason, just forgot to remove it after switching out the button components

**Review by bchrobot — APPROVED** [review]
