### PR TITLE
fix: fix csv header validation

### LINKED ISSUE #1133: Uploading a contact list with "firsstName" column and upload is stuck
**Describe the bug**
The client tried to upload a contact list and added an extra S in the firstName column, making it "firsstName." The problem is that the upload appeared to be stuck and there was no error indication.

**To Reproduce**

1.  Upload a csv with one of the columns reading firsstName 
1.  File is stuck, received no error message

**Expected behavior**

User receives an error and is able to correct the file.

### PR DESCRIPTION
**Pull request by bchrobot**
## Description

This PR does two things:

1. Trims whitespace around column names
2. Fixes error display in the client

## Motivation and Context

Closes #1133.

## How Has This Been Tested?

This has been tested locally.

## Screenshots (if appropriate):

N/A

## Documentation Changes

N/A

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

### CODE REVIEW

**Review by hiemanshu — APPROVED** [review]

File: src/containers/AdminCampaignEdit/sections/CampaignContactsForm/index.tsx [hunk 1]
```diff
@@ -140,7 +140,7 @@ class CampaignContactsForm extends React.Component<
         excludeCampaignIds: selectedCampaignIds
       };
       const response = await this.props.mutations.editCampaign(campaignInput);
-      if (response.errors) throw response.errors;
+      if (response.errors) throw response.errors[0];
```
Comment (ajohn25) [inline src/containers/AdminCampaignEdit/sections/CampaignContactsForm/index.tsx:143]: Question: Were you able to figure out if this was needed because of changes in #1027 or somewhere else?

**Review by ajohn25 — APPROVED** [review]

File: src/containers/AdminCampaignEdit/sections/CampaignContactsForm/index.tsx (hunk 1 above)
Comment (bchrobot) [reply src/containers/AdminCampaignEdit/sections/CampaignContactsForm/index.tsx:143]: I think it's actually more likely that it was broken in #644 but I haven't stepped through to confirm that.

Comment (bchrobot) [reply src/containers/AdminCampaignEdit/sections/CampaignContactsForm/index.tsx:143]: [v2 ApolloQueryResult](https://www.apollographql.com/docs/react/v2/api/apollo-client#types) has both `error` and `errors` properties. v3 exports ([1](https://github.com/apollographql/apollo-client/blob/dc0c7d1e3a9e43452737be17c3b75c90d1d7130c/src/core/QueryManager.ts#L178), [2](https://github.com/apollographql/apollo-client/blob/dc0c7d1e3a9e43452737be17c3b75c90d1d7130c/src/link/core/types.ts#L23-L31)) `graphql`'s [`ExecutionResult`](https://github.com/graphql/graphql-js/blob/52231d1b61911c2de05b06018e629afb412fd61a/src/execution/execute.ts#L127-L134) which only has `errors`.

They redid the documentation site recently with better v2 support but for a while it was tricky to find good answers about how to do what we wanted, especially with the `loadData()` HOC, with v2. I think we just got sloppy/confused by v3 documentation and started throwing `errors` as standard practice. `loadData()` handles that okay but in other situations, like here, it didn't work but also didn't noisily break anything so we didn't notice.
